In [16]:
from pathfinding.core.grid import Grid
from pathfinding.finder.a_star import AStarFinder

matrix = [
    [1,1,1,1,1,1],
    [1,0,1,1,1,1],
    [1,1,1,1,1,1]
    ]

grid = Grid(matrix = matrix)

start = grid.node(0,0)
end = grid.node(5,2)

finder = AStarFinder()

path, run = finder.find_path(start, end, grid)

print(path)

[<GridNode(0:0 0x23b39a9a070)>, <GridNode(1:0 0x23b39a9ab80)>, <GridNode(2:0 0x23b39a9abb0)>, <GridNode(3:0 0x23b4127fe20)>, <GridNode(4:0 0x23b4127f370)>, <GridNode(5:0 0x23b4127ffa0)>, <GridNode(5:1 0x23b3823cf40)>, <GridNode(5:2 0x23b3823caf0)>]


#### IMAGE TO MATRIX CODE

In [17]:
import cv2
import numpy as np

def image_to_matrix(image):
  """Converts an image to a matrix of 1s (free space) and 0s (obstacles)"""
  # Convert image to grayscale (assuming black and white)
  gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

  # Threshold the image to create binary representation (white: 255, black: 0)
  _, binary_image = cv2.threshold(gray_image, 127, 255, cv2.THRESH_BINARY)

  # Convert white pixels (255) to 1 and black pixels (0) to 0
  return np.where(binary_image == 255, 1, 0)

# Example usage
image = cv2.imread("C:\\Users\\vyas\\Desktop\\ROBOT PROJECT CODES\\floorplan.png")
matrix = image_to_matrix(image)

# Print the matrix (optional)
print(matrix)

[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]


In [18]:
from pathfinding.core.grid import Grid
from pathfinding.finder.a_star import AStarFinder
import cv2
import numpy as np

def image_to_matrix(image):
  """Converts an image to a matrix of 1s (free space) and 0s (obstacles)"""
  # Convert image to grayscale (assuming black and white)
  gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

  # Threshold the image to create binary representation (white: 255, black: 0)
  _, binary_image = cv2.threshold(gray_image, 127, 255, cv2.THRESH_BINARY)

  # Convert white pixels (255) to 1 and black pixels (0) to 0
  return np.where(binary_image == 255, 1, 0)

# Example usage
image = cv2.imread("C:\\Users\\vyas\\Desktop\\ROBOT PROJECT CODES\\floorplan.png")
matrix = image_to_matrix(image)

grid = Grid(matrix = matrix)

start = grid.node(0,0)
end = grid.node(5,2)

finder = AStarFinder()

path, run = finder.find_path(start, end, grid)

print(path)

[<GridNode(0:0 0x23b423b8730)>, <GridNode(1:0 0x23b423b8f40)>, <GridNode(2:0 0x23b423b8fd0)>, <GridNode(3:0 0x23b423b83d0)>, <GridNode(4:0 0x23b423b8ac0)>, <GridNode(5:0 0x23b423b8310)>, <GridNode(5:1 0x23b4323b940)>, <GridNode(5:2 0x23b43277c70)>]


#### CODE TO STORE START AND END NODES BY CLICKING THE IMAGE

In [19]:
import cv2

# Variables to store click coordinates
click_count = 0
start = None
end = None

def click_event(event, x, y, flags, params):
    global click_count, start, end, img

    if event == cv2.EVENT_LBUTTONDOWN:
        if click_count == 0:
            start = (x, y)
            click_count += 1
        elif click_count == 1:
            end = (x, y)
            click_count += 1
            print("Start coordinates:", start)
            print("End coordinates:", end)
            cv2.destroyAllWindows()  # Close the window after two clicks

if __name__ == "__main__":
    img = cv2.imread("C:\\Users\\vyas\\Desktop\\ROBOT PROJECT CODES\\floorplan.png")
    cv2.imshow('image', img)
    cv2.setMouseCallback('image', click_event)
    cv2.waitKey(0)


Start coordinates: (217, 44)
End coordinates: (63, 124)


#### CODE TO FIND A* PATH FROM START TO END NODES(CLICKING ON IMAGE TO GET THE START AND END NODES)

In [22]:
from pathfinding.core.grid import Grid
from pathfinding.finder.a_star import AStarFinder
import cv2
import numpy as np

# Variables to store click coordinates
click_count = 0
start = None
end = None

def click_event(event, x, y, flags, params):
    global click_count, start, end, img

    if event == cv2.EVENT_LBUTTONDOWN:
        if click_count == 0:
            start = (x, y)
            click_count += 1
        elif click_count == 1:
            end = (x, y)
            click_count += 1
            print("Start coordinates:", start)
            print("End coordinates:", end)
            cv2.destroyAllWindows()  # Close the window after two clicks

def image_to_matrix(image):
  """Converts an image to a matrix of 1s (free space) and 0s (obstacles)"""
  # Convert image to grayscale (assuming black and white)
  gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

  # Threshold the image to create binary representation (white: 255, black: 0)
  _, binary_image = cv2.threshold(gray_image, 127, 255, cv2.THRESH_BINARY)

  # Convert white pixels (255) to 1 and black pixels (0) to 0
  return np.where(binary_image == 255, 1, 0)

if __name__ == "__main__":
    img = cv2.imread("C:\\Users\\vyas\\Desktop\\ROBOT PROJECT CODES\\floorplan.png")
    cv2.imshow('image', img)
    cv2.setMouseCallback('image', click_event)
    cv2.waitKey(0)
    
    matrix = image_to_matrix(img)

    grid = Grid(matrix = matrix)
    
    startNode = grid.node(start[0],start[1])
    endNode = grid.node(end[0], end[1])
    
    finder = AStarFinder()
    path, run = finder.find_path(startNode, endNode, grid)
    
    print(path)

Start coordinates: (185, 66)
End coordinates: (215, 154)
[<GridNode(185:66 0x23b418f7e20)>, <GridNode(186:66 0x23b418f7e50)>, <GridNode(187:66 0x23b418f7e80)>, <GridNode(188:66 0x23b418f7eb0)>, <GridNode(189:66 0x23b418f7ee0)>, <GridNode(190:66 0x23b418f7f10)>, <GridNode(191:66 0x23b418f7f40)>, <GridNode(192:66 0x23b418f7f70)>, <GridNode(193:66 0x23b418f7fa0)>, <GridNode(194:66 0x23b418f7fd0)>, <GridNode(195:66 0x23b418fd040)>, <GridNode(196:66 0x23b418fd070)>, <GridNode(197:66 0x23b418fd0a0)>, <GridNode(198:66 0x23b418fd0d0)>, <GridNode(199:66 0x23b418fd100)>, <GridNode(200:66 0x23b418fd130)>, <GridNode(201:66 0x23b418fd160)>, <GridNode(202:66 0x23b418fd190)>, <GridNode(203:66 0x23b418fd1c0)>, <GridNode(204:66 0x23b418fd1f0)>, <GridNode(205:66 0x23b418fd220)>, <GridNode(206:66 0x23b418fd250)>, <GridNode(207:66 0x23b418fd280)>, <GridNode(208:66 0x23b418fd2b0)>, <GridNode(209:66 0x23b418fd2e0)>, <GridNode(210:66 0x23b418fd310)>, <GridNode(211:66 0x23b418fd340)>, <GridNode(212:66 0x23b41

#### CODE TO EXTRACT (x,y) COORDINATES OF EACH ELEMENT IN THE PATH 

In [23]:
points = []
for point in path:
    x = point.x
    y = point.y
    print((x, y), end = " ")
    points.append((x,y))

(185, 66) (186, 66) (187, 66) (188, 66) (189, 66) (190, 66) (191, 66) (192, 66) (193, 66) (194, 66) (195, 66) (196, 66) (197, 66) (198, 66) (199, 66) (200, 66) (201, 66) (202, 66) (203, 66) (204, 66) (205, 66) (206, 66) (207, 66) (208, 66) (209, 66) (210, 66) (211, 66) (212, 66) (213, 66) (214, 66) (215, 66) (215, 67) (215, 68) (215, 69) (215, 70) (215, 71) (215, 72) (215, 73) (215, 74) (215, 75) (215, 76) (215, 77) (215, 78) (215, 79) (215, 80) (215, 81) (215, 82) (215, 83) (215, 84) (215, 85) (215, 86) (215, 87) (215, 88) (215, 89) (215, 90) (215, 91) (215, 92) (215, 93) (215, 94) (215, 95) (215, 96) (215, 97) (215, 98) (215, 99) (215, 100) (215, 101) (215, 102) (215, 103) (215, 104) (215, 105) (215, 106) (215, 107) (215, 108) (215, 109) (215, 110) (215, 111) (215, 112) (215, 113) (215, 114) (215, 115) (215, 116) (215, 117) (215, 118) (215, 119) (215, 120) (215, 121) (215, 122) (215, 123) (215, 124) (215, 125) (215, 126) (215, 127) (215, 128) (215, 129) (215, 130) (215, 131) (215, 13

In [24]:
for i in points:
    print(i)

(185, 66)
(186, 66)
(187, 66)
(188, 66)
(189, 66)
(190, 66)
(191, 66)
(192, 66)
(193, 66)
(194, 66)
(195, 66)
(196, 66)
(197, 66)
(198, 66)
(199, 66)
(200, 66)
(201, 66)
(202, 66)
(203, 66)
(204, 66)
(205, 66)
(206, 66)
(207, 66)
(208, 66)
(209, 66)
(210, 66)
(211, 66)
(212, 66)
(213, 66)
(214, 66)
(215, 66)
(215, 67)
(215, 68)
(215, 69)
(215, 70)
(215, 71)
(215, 72)
(215, 73)
(215, 74)
(215, 75)
(215, 76)
(215, 77)
(215, 78)
(215, 79)
(215, 80)
(215, 81)
(215, 82)
(215, 83)
(215, 84)
(215, 85)
(215, 86)
(215, 87)
(215, 88)
(215, 89)
(215, 90)
(215, 91)
(215, 92)
(215, 93)
(215, 94)
(215, 95)
(215, 96)
(215, 97)
(215, 98)
(215, 99)
(215, 100)
(215, 101)
(215, 102)
(215, 103)
(215, 104)
(215, 105)
(215, 106)
(215, 107)
(215, 108)
(215, 109)
(215, 110)
(215, 111)
(215, 112)
(215, 113)
(215, 114)
(215, 115)
(215, 116)
(215, 117)
(215, 118)
(215, 119)
(215, 120)
(215, 121)
(215, 122)
(215, 123)
(215, 124)
(215, 125)
(215, 126)
(215, 127)
(215, 128)
(215, 129)
(215, 130)
(215, 131)
(215, 13

#### LOGIC TO GET THE DIRECTION TO MOVE TO NEXT COORDINATE

In [25]:
x = 0
directions = []
while(x < len(points)):
    if(x == 0):
        x+=1
        continue
    else:
        if(points[x-1][0] < points[x][0]):
            direction = "east"
            x+=1
        elif(points[x-1][0] > points[x][0]):
            direction = "west"
            x+=1
        elif(points[x-1][1] < points[x][1]):
            direction = "south"
            x+=1
        elif(points[x-1][1] > points[x][1]):
            direction = "north"
            x+=1
        directions.append(direction)
            
    

#### TO STORE THE NUMBER OF TIMES ONE COMMAND HAS OCCURRED CONSECUTIVELY

In [26]:
x = 0
count = 0
command = directions[0]
commands = []
for direction in directions:
    if (command == direction):
        count+=1
        x+=1
    if (x+1 == len(directions)):
        if(command == direction):
            count+=1
            commands.append((command, count))
            continue
        else:
            commands.append((command, count))
            command = direction
            count = 1
            commands((command, count))
    
    if (command != direction):
        commands.append((command, count))
        command = direction
        count = 1
        x+=1

print(commands)


[('east', 30), ('south', 88)]


#### OVERALL CODE CONTAINING IMPORTING FUNCTIONALITY FROM ABOVE

#### Click on image to start and end nodes
#### Convert image to grid and find A* path
#### Extract coordinates of each element in path and find directions to move in 
#### Store the number of times one command is published consecutively

In [1]:
from pathfinding.core.grid import Grid
from pathfinding.finder.a_star import AStarFinder
import cv2
import numpy as np

# Variables to store click coordinates
click_count = 0
start = None
end = None

### Function to click the image and store start and end nodes
def click_event(event, x, y, flags, params):
    global click_count, start, end, img

    if event == cv2.EVENT_LBUTTONDOWN:
        if click_count == 0:
            start = (x, y)
            click_count += 1
        elif click_count == 1:
            end = (x, y)
            click_count += 1
            print("Start coordinates:", start)
            print("End coordinates:", end)
            cv2.destroyAllWindows()  # Close the window after two clicks

### Function to convert image to matrix
def image_to_matrix(image):
  """Converts an image to a matrix of 1s (free space) and 0s (obstacles)"""
  # Convert image to grayscale (assuming black and white)
  gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

  # Threshold the image to create binary representation (white: 255, black: 0)
  _, binary_image = cv2.threshold(gray_image, 240, 255, cv2.THRESH_BINARY)

  # Convert white pixels (255) to 1 and black pixels (0) to 0
  return np.where(binary_image == 255, 1, 0)



if __name__ == "__main__":
    img = cv2.imread("C:\\Users\\vyas\\Desktop\\ROBOT PROJECT CODES\\floorplan.png")
    cv2.imshow('image', img)
    cv2.setMouseCallback('image', click_event)
    cv2.waitKey(0)
    
    matrix = image_to_matrix(img)

    grid = Grid(matrix = matrix)
    
    startNode = grid.node(start[0],start[1])
    endNode = grid.node(end[0], end[1])
    
    finder = AStarFinder()
    path, run = finder.find_path(startNode, endNode, grid)
    
    #print(path)
    
    
    ### Extracting coordinates of each element in the path
    points = []
    for point in path:
        x = point.x
        y = point.y
        #print((x, y), end = " ")
        points.append((x,y))
        
    ### LOGIC TO GET THE DIRECTION TO MOVE TO NEXT COORDINATE and STORE IN LIST
    x = 0
    directions = []
    while(x < len(points)):
        if(x == 0):
            x+=1
            continue
        else:
            if(points[x-1][0] < points[x][0]):
                direction = "east"
                x+=1
            elif(points[x-1][0] > points[x][0]):
                direction = "west"
                x+=1
            elif(points[x-1][1] < points[x][1]):
                direction = "south"
                x+=1
            elif(points[x-1][1] > points[x][1]):
                direction = "north"
                x+=1
        directions.append(direction)
        
    ### TO STORE THE NUMBER OF TIMES ONE COMMAND HAS OCCURRED CONSECUTIVELY
    x = 0
    count = 0
    if(len(directions) > 0):
        command = directions[0]
    else:
        print("Path cannot be found")
        exit()
    commands = []
    for direction in directions:
        if (command == direction):
            count+=1
            x+=1
            if (x+1 == len(directions)):
                if(command == direction):
                    count+=1
                    commands.append((command, count))
                    continue
                else:
                    commands.append((command, count))
                    command = direction
                    count = 1
                    commands((command, count))
    
        if (command != direction):
            commands.append((command, count))
            command = direction
            count = 1
            x+=1
    print()
    print(commands)
    

Start coordinates: (195, 113)
End coordinates: (82, 135)

[('west', 104), ('north', 18), ('west', 15), ('south', 9), ('east', 1), ('south', 2), ('east', 1), ('south', 2), ('east', 1), ('south', 1), ('east', 1), ('south', 1), ('east', 1), ('south', 1), ('east', 1), ('south', 24)]
