In [41]:
from pathfinding.core.grid import Grid
from pathfinding.finder.a_star import AStarFinder

matrix = [
    [1,1,1,1,1,1],
    [1,0,1,1,1,1],
    [1,1,1,1,1,1]
    ]

grid = Grid(matrix = matrix)

start = grid.node(0,0)
end = grid.node(5,2)

finder = AStarFinder()

path, run = finder.find_path(start, end, grid)

print(path)

[<GridNode(0:0 0x264d8a684c0)>, <GridNode(1:0 0x264d8a68820)>, <GridNode(2:0 0x264d8a682e0)>, <GridNode(3:0 0x264d8a68850)>, <GridNode(4:0 0x264d8a689d0)>, <GridNode(5:0 0x264d8a68520)>, <GridNode(5:1 0x264d8a68be0)>, <GridNode(5:2 0x264d8a68a90)>]


In [7]:
from pathfinding.core.grid import Grid
from pathfinding.finder.a_star import AStarFinder
import pygame, sys
import cv2
import numpy as np

def image_to_matrix(image):
  """Converts an image to a matrix of 1s (free space) and 0s (obstacles)"""
  # Convert image to grayscale (assuming black and white)
  gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

  # Threshold the image to create binary representation (white: 255, black: 0)
  _, binary_image = cv2.threshold(gray_image, 127, 255, cv2.THRESH_BINARY)

  # Convert white pixels (255) to 1 and black pixels (0) to 0
  return np.where(binary_image == 255, 1, 0)

pygame.init()
screen = pygame.display.set_mode((1280,736))
img = "C:\\Users\\vyas\\Desktop\\ROBOT PROJECT CODES\\floorplan.png"
bg_surf = pygame.image.load("C:\\Users\\vyas\\Desktop\\ROBOT PROJECT CODES\\floorplan.png").convert()

matrix = image_to_matrix("C:\\Users\\vyas\\Desktop\\ROBOT PROJECT CODES\\floorplan.png")

while True:
    for event in pygame.event.get():
        if event.type == pygame.QUIT:
            pygame.quit()
            sys.exit()

    screen.blit(bg_surf, (0,0))
    pygame.display.update()
    clock.tick(60)

error: OpenCV(4.9.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src is not a numpy array, neither a scalar
>  - Expected Ptr<cv::UMat> for argument 'src'


In [2]:
import cv2
import numpy as np

def image_to_matrix(image):
  """Converts an image to a matrix of 1s (free space) and 0s (obstacles)"""
  # Convert image to grayscale (assuming black and white)
  gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

  # Threshold the image to create binary representation (white: 255, black: 0)
  _, binary_image = cv2.threshold(gray_image, 127, 255, cv2.THRESH_BINARY)

  # Convert white pixels (255) to 1 and black pixels (0) to 0
  return np.where(binary_image == 255, 1, 0)

# Example usage
image = cv2.imread("C:\\Users\\vyas\\Desktop\\ROBOT PROJECT CODES\\floorplan.png")
matrix = image_to_matrix(image)

# Print the matrix (optional)
print(matrix)

[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]


In [8]:
from pathfinding.core.grid import Grid
from pathfinding.finder.a_star import AStarFinder
import cv2
import numpy as np

def image_to_matrix(image):
  """Converts an image to a matrix of 1s (free space) and 0s (obstacles)"""
  # Convert image to grayscale (assuming black and white)
  gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

  # Threshold the image to create binary representation (white: 255, black: 0)
  _, binary_image = cv2.threshold(gray_image, 127, 255, cv2.THRESH_BINARY)

  # Convert white pixels (255) to 1 and black pixels (0) to 0
  return np.where(binary_image == 255, 1, 0)

# Example usage
image = cv2.imread("C:\\Users\\vyas\\Desktop\\ROBOT PROJECT CODES\\floorplan.png")
matrix = image_to_matrix(image)

grid = Grid(matrix = matrix)

start = grid.node(0,0)
end = grid.node(5,2)

finder = AStarFinder()

path, run = finder.find_path(start, end, grid)

print(path)

[<GridNode(0:0 0x264d818df40)>, <GridNode(1:0 0x264d818dac0)>, <GridNode(2:0 0x264d818dd30)>, <GridNode(3:0 0x264d818d3d0)>, <GridNode(4:0 0x264d818d6a0)>, <GridNode(5:0 0x264d818d490)>, <GridNode(5:1 0x264d81d3550)>, <GridNode(5:2 0x264d69e1940)>]


In [11]:
import cv2

# Variables to store click coordinates
click_count = 0
start = None
end = None

def click_event(event, x, y, flags, params):
    global click_count, start, end, img

    if event == cv2.EVENT_LBUTTONDOWN:
        if click_count == 0:
            start = (x, y)
            click_count += 1
        elif click_count == 1:
            end = (x, y)
            click_count += 1
            print("Start coordinates:", start)
            print("End coordinates:", end)
            cv2.destroyAllWindows()  # Close the window after two clicks

if __name__ == "__main__":
    img = cv2.imread("C:\\Users\\vyas\\Desktop\\ROBOT PROJECT CODES\\floorplan.png")
    cv2.imshow('image', img)
    cv2.setMouseCallback('image', click_event)
    cv2.waitKey(0)


Start coordinates: (138, 73)
End coordinates: (204, 125)


In [39]:
from pathfinding.core.grid import Grid
from pathfinding.finder.a_star import AStarFinder
import cv2
import numpy as np

# Variables to store click coordinates
click_count = 0
start = None
end = None

def click_event(event, x, y, flags, params):
    global click_count, start, end, img

    if event == cv2.EVENT_LBUTTONDOWN:
        if click_count == 0:
            start = (x, y)
            click_count += 1
        elif click_count == 1:
            end = (x, y)
            click_count += 1
            print("Start coordinates:", start)
            print("End coordinates:", end)
            cv2.destroyAllWindows()  # Close the window after two clicks

def image_to_matrix(image):
  """Converts an image to a matrix of 1s (free space) and 0s (obstacles)"""
  # Convert image to grayscale (assuming black and white)
  gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

  # Threshold the image to create binary representation (white: 255, black: 0)
  _, binary_image = cv2.threshold(gray_image, 127, 255, cv2.THRESH_BINARY)

  # Convert white pixels (255) to 1 and black pixels (0) to 0
  return np.where(binary_image == 255, 1, 0)

if __name__ == "__main__":
    img = cv2.imread("C:\\Users\\vyas\\Desktop\\ROBOT PROJECT CODES\\floorplan.png")
    cv2.imshow('image', img)
    cv2.setMouseCallback('image', click_event)
    cv2.waitKey(0)
    
    matrix = image_to_matrix(img)

    grid = Grid(matrix = matrix)
    
    startNode = grid.node(start[0],start[1])
    endNode = grid.node(end[0], end[1])
    
    finder = AStarFinder()
    path, run = finder.find_path(startNode, endNode, grid)
    
    print(path)

Start coordinates: (138, 78)
End coordinates: (34, 138)
[<GridNode(138:78 0x264d9038c70)>, <GridNode(138:79 0x264d90510a0)>, <GridNode(138:80 0x264d9063490)>, <GridNode(138:81 0x264d9075880)>, <GridNode(138:82 0x264d9087c70)>, <GridNode(138:83 0x264d8b60fa0)>, <GridNode(138:84 0x264d8aaa1f0)>, <GridNode(138:85 0x264d90985e0)>, <GridNode(138:86 0x264d954c9d0)>, <GridNode(138:87 0x264d8edcdc0)>, <GridNode(138:88 0x264d90aa1f0)>, <GridNode(138:89 0x264d90b85e0)>, <GridNode(138:90 0x264d90c79d0)>, <GridNode(138:91 0x264d90d5dc0)>, <GridNode(138:92 0x264d90e81f0)>, <GridNode(138:93 0x264d90f65e0)>, <GridNode(138:94 0x264d91049d0)>, <GridNode(138:95 0x264d9112dc0)>, <GridNode(138:96 0x264d91241f0)>, <GridNode(138:97 0x264d91325e0)>, <GridNode(138:98 0x264d91419d0)>, <GridNode(138:99 0x264d914fdc0)>, <GridNode(138:100 0x264d91621f0)>, <GridNode(138:101 0x264d91725e0)>, <GridNode(138:102 0x264d91849d0)>, <GridNode(138:103 0x264d9196dc0)>, <GridNode(138:104 0x264d91ad1f0)>, <GridNode(138:105 0x

In [30]:
points = []
for point in path:
    x = point.x
    y = point.y
    print((x, y), end = " ")
    points.append((x,y))

(127, 44) (128, 44) (129, 44) (130, 44) (131, 44) (132, 44) (133, 44) (134, 44) (135, 44) (136, 44) (137, 44) (138, 44) (139, 44) (140, 44) (141, 44) (142, 44) (143, 44) (144, 44) (145, 44) (146, 44) (147, 44) (148, 44) (149, 44) (150, 44) (151, 44) (152, 44) (153, 44) (154, 44) (155, 44) (156, 44) (157, 44) (158, 44) (159, 44) (160, 44) (161, 44) (162, 44) (163, 44) (164, 44) (165, 44) (166, 44) (167, 44) (168, 44) (169, 44) (170, 44) (171, 44) (172, 44) (173, 44) (174, 44) (175, 44) (176, 44) (177, 44) (178, 44) (179, 44) (180, 44) (181, 44) (182, 44) (183, 44) (184, 44) (185, 44) (186, 44) (187, 44) (188, 44) (189, 44) (190, 44) (191, 44) (192, 44) (193, 44) (194, 44) (195, 44) (196, 44) (197, 44) (198, 44) (199, 44) (200, 44) (201, 44) (202, 44) (203, 44) (204, 44) (205, 44) (206, 44) (207, 44) (208, 44) (209, 44) (210, 44) (211, 44) (211, 45) (211, 46) (211, 47) (211, 48) (211, 49) (211, 50) (211, 51) (211, 52) (211, 53) (211, 54) (211, 55) (211, 56) (211, 57) (211, 58) (211, 59) 

In [31]:
for i in points:
    print(i)

(127, 44)
(128, 44)
(129, 44)
(130, 44)
(131, 44)
(132, 44)
(133, 44)
(134, 44)
(135, 44)
(136, 44)
(137, 44)
(138, 44)
(139, 44)
(140, 44)
(141, 44)
(142, 44)
(143, 44)
(144, 44)
(145, 44)
(146, 44)
(147, 44)
(148, 44)
(149, 44)
(150, 44)
(151, 44)
(152, 44)
(153, 44)
(154, 44)
(155, 44)
(156, 44)
(157, 44)
(158, 44)
(159, 44)
(160, 44)
(161, 44)
(162, 44)
(163, 44)
(164, 44)
(165, 44)
(166, 44)
(167, 44)
(168, 44)
(169, 44)
(170, 44)
(171, 44)
(172, 44)
(173, 44)
(174, 44)
(175, 44)
(176, 44)
(177, 44)
(178, 44)
(179, 44)
(180, 44)
(181, 44)
(182, 44)
(183, 44)
(184, 44)
(185, 44)
(186, 44)
(187, 44)
(188, 44)
(189, 44)
(190, 44)
(191, 44)
(192, 44)
(193, 44)
(194, 44)
(195, 44)
(196, 44)
(197, 44)
(198, 44)
(199, 44)
(200, 44)
(201, 44)
(202, 44)
(203, 44)
(204, 44)
(205, 44)
(206, 44)
(207, 44)
(208, 44)
(209, 44)
(210, 44)
(211, 44)
(211, 45)
(211, 46)
(211, 47)
(211, 48)
(211, 49)
(211, 50)
(211, 51)
(211, 52)
(211, 53)
(211, 54)
(211, 55)
(211, 56)
(211, 57)
(211, 58)
(211, 59)


In [38]:
x = 0
while(x < len(points)):
    if(x == 0):
        x+=1
        continue
    else:
        if(points[x-1][0] < points[x][0]):
            print("east")
            x+=1
        elif(points[x-1][0] > points[x][0]):
            print("west")
            x+=1
        elif(points[x-1][1] < points[x][1]):
            print("south")
            x+=1
        elif(points[x-1][1] > points[x][1]):
            print("north")
            x+=1
            
    

east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
east
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
south
sout