In [41]:
from pathfinding.core.grid import Grid
from pathfinding.finder.a_star import AStarFinder

matrix = [
    [1,1,1,1,1,1],
    [1,0,1,1,1,1],
    [1,1,1,1,1,1]
    ]

grid = Grid(matrix = matrix)

start = grid.node(0,0)
end = grid.node(5,2)

finder = AStarFinder()

path, run = finder.find_path(start, end, grid)

print(path)

[<GridNode(0:0 0x264d8a684c0)>, <GridNode(1:0 0x264d8a68820)>, <GridNode(2:0 0x264d8a682e0)>, <GridNode(3:0 0x264d8a68850)>, <GridNode(4:0 0x264d8a689d0)>, <GridNode(5:0 0x264d8a68520)>, <GridNode(5:1 0x264d8a68be0)>, <GridNode(5:2 0x264d8a68a90)>]


#### IMAGE TO MATRIX CODE

In [2]:
import cv2
import numpy as np

def image_to_matrix(image):
  """Converts an image to a matrix of 1s (free space) and 0s (obstacles)"""
  # Convert image to grayscale (assuming black and white)
  gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

  # Threshold the image to create binary representation (white: 255, black: 0)
  _, binary_image = cv2.threshold(gray_image, 127, 255, cv2.THRESH_BINARY)

  # Convert white pixels (255) to 1 and black pixels (0) to 0
  return np.where(binary_image == 255, 1, 0)

# Example usage
image = cv2.imread("C:\\Users\\vyas\\Desktop\\ROBOT PROJECT CODES\\floorplan.png")
matrix = image_to_matrix(image)

# Print the matrix (optional)
print(matrix)

[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]


In [15]:
from pathfinding.core.grid import Grid
from pathfinding.finder.a_star import AStarFinder
import cv2
import numpy as np

def image_to_matrix(image):
  """Converts an image to a matrix of 1s (free space) and 0s (obstacles)"""
  # Convert image to grayscale (assuming black and white)
  gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

  # Threshold the image to create binary representation (white: 255, black: 0)
  _, binary_image = cv2.threshold(gray_image, 127, 255, cv2.THRESH_BINARY)

  # Convert white pixels (255) to 1 and black pixels (0) to 0
  return np.where(binary_image == 255, 1, 0)

# Example usage
image = cv2.imread("C:\\Users\\vyas\\Desktop\\ROBOT PROJECT CODES\\floorplan.png")
matrix = image_to_matrix(image)

grid = Grid(matrix = matrix)

start = grid.node(0,0)
end = grid.node(5,2)

finder = AStarFinder()

path, run = finder.find_path(start, end, grid)

print(path)

[<GridNode(0:0 0x23b4127ff10)>, <GridNode(1:0 0x23b4127ff40)>, <GridNode(2:0 0x23b4127fee0)>, <GridNode(3:0 0x23b4127f3a0)>, <GridNode(4:0 0x23b4127ff70)>, <GridNode(5:0 0x23b39a1f220)>, <GridNode(5:1 0x23b382625e0)>, <GridNode(5:2 0x23b382489d0)>]


#### CODE TO STORE START AND END NODES BY CLICKING THE IMAGE

In [11]:
import cv2

# Variables to store click coordinates
click_count = 0
start = None
end = None

def click_event(event, x, y, flags, params):
    global click_count, start, end, img

    if event == cv2.EVENT_LBUTTONDOWN:
        if click_count == 0:
            start = (x, y)
            click_count += 1
        elif click_count == 1:
            end = (x, y)
            click_count += 1
            print("Start coordinates:", start)
            print("End coordinates:", end)
            cv2.destroyAllWindows()  # Close the window after two clicks

if __name__ == "__main__":
    img = cv2.imread("C:\\Users\\vyas\\Desktop\\ROBOT PROJECT CODES\\floorplan.png")
    cv2.imshow('image', img)
    cv2.setMouseCallback('image', click_event)
    cv2.waitKey(0)


Start coordinates: (138, 73)
End coordinates: (204, 125)


#### CODE TO FIND A* PATH FROM START TO END NODES(CLICKING ON IMAGE TO GET THE START AND END NODES)

In [3]:
from pathfinding.core.grid import Grid
from pathfinding.finder.a_star import AStarFinder
import cv2
import numpy as np

# Variables to store click coordinates
click_count = 0
start = None
end = None

def click_event(event, x, y, flags, params):
    global click_count, start, end, img

    if event == cv2.EVENT_LBUTTONDOWN:
        if click_count == 0:
            start = (x, y)
            click_count += 1
        elif click_count == 1:
            end = (x, y)
            click_count += 1
            print("Start coordinates:", start)
            print("End coordinates:", end)
            cv2.destroyAllWindows()  # Close the window after two clicks

def image_to_matrix(image):
  """Converts an image to a matrix of 1s (free space) and 0s (obstacles)"""
  # Convert image to grayscale (assuming black and white)
  gray_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

  # Threshold the image to create binary representation (white: 255, black: 0)
  _, binary_image = cv2.threshold(gray_image, 127, 255, cv2.THRESH_BINARY)

  # Convert white pixels (255) to 1 and black pixels (0) to 0
  return np.where(binary_image == 255, 1, 0)

if __name__ == "__main__":
    img = cv2.imread("C:\\Users\\vyas\\Desktop\\ROBOT PROJECT CODES\\floorplan.png")
    cv2.imshow('image', img)
    cv2.setMouseCallback('image', click_event)
    cv2.waitKey(0)
    
    matrix = image_to_matrix(img)

    grid = Grid(matrix = matrix)
    
    startNode = grid.node(start[0],start[1])
    endNode = grid.node(end[0], end[1])
    
    finder = AStarFinder()
    path, run = finder.find_path(startNode, endNode, grid)
    
    print(path)

Start coordinates: (214, 49)
End coordinates: (122, 133)
[<GridNode(214:49 0x23b43229a30)>, <GridNode(214:50 0x23b4323be20)>, <GridNode(214:51 0x23b43253250)>, <GridNode(214:52 0x23b43265640)>, <GridNode(214:53 0x23b43277a30)>, <GridNode(214:54 0x23b43289e20)>, <GridNode(214:55 0x23b432a0250)>, <GridNode(214:56 0x23b432b2640)>, <GridNode(214:57 0x23b432c5a30)>, <GridNode(214:58 0x23b432d7e20)>, <GridNode(214:59 0x23b432f0250)>, <GridNode(214:60 0x23b43302640)>, <GridNode(214:61 0x23b43314a30)>, <GridNode(214:62 0x23b43326e20)>, <GridNode(214:63 0x23b4333d250)>, <GridNode(214:64 0x23b4334f640)>, <GridNode(214:65 0x23b43362a30)>, <GridNode(214:66 0x23b43374e20)>, <GridNode(214:67 0x23b4338d250)>, <GridNode(214:68 0x23b4339f640)>, <GridNode(214:69 0x23b433b1a30)>, <GridNode(214:70 0x23b433c3e20)>, <GridNode(214:71 0x23b433da250)>, <GridNode(214:72 0x23b433ec640)>, <GridNode(214:73 0x23b433ffa30)>, <GridNode(214:74 0x23b43411e20)>, <GridNode(214:75 0x23b43429250)>, <GridNode(214:76 0x23b43

#### CODE TO EXTRACT (x,y) COORDINATES OF EACH ELEMENT IN THE PATH 

In [5]:
points = []
for point in path:
    x = point.x
    y = point.y
    print((x, y), end = " ")
    points.append((x,y))

(214, 49) (214, 50) (214, 51) (214, 52) (214, 53) (214, 54) (214, 55) (214, 56) (214, 57) (214, 58) (214, 59) (214, 60) (214, 61) (214, 62) (214, 63) (214, 64) (214, 65) (214, 66) (214, 67) (214, 68) (214, 69) (214, 70) (214, 71) (214, 72) (214, 73) (214, 74) (214, 75) (214, 76) (214, 77) (214, 78) (214, 79) (214, 80) (214, 81) (214, 82) (214, 83) (214, 84) (214, 85) (214, 86) (214, 87) (214, 88) (214, 89) (214, 90) (214, 91) (214, 92) (214, 93) (214, 94) (214, 95) (214, 96) (214, 97) (214, 98) (214, 99) (214, 100) (214, 101) (214, 102) (214, 103) (214, 104) (214, 105) (214, 106) (214, 107) (214, 108) (214, 109) (214, 110) (214, 111) (214, 112) (214, 113) (214, 114) (214, 115) (214, 116) (214, 117) (214, 118) (214, 119) (214, 120) (214, 121) (214, 122) (214, 123) (214, 124) (214, 125) (214, 126) (214, 127) (214, 128) (214, 129) (214, 130) (214, 131) (214, 132) (214, 133) (213, 133) (212, 133) (211, 133) (210, 133) (209, 133) (208, 133) (207, 133) (206, 133) (205, 133) (204, 133) (203, 

In [6]:
for i in points:
    print(i)

(214, 49)
(214, 50)
(214, 51)
(214, 52)
(214, 53)
(214, 54)
(214, 55)
(214, 56)
(214, 57)
(214, 58)
(214, 59)
(214, 60)
(214, 61)
(214, 62)
(214, 63)
(214, 64)
(214, 65)
(214, 66)
(214, 67)
(214, 68)
(214, 69)
(214, 70)
(214, 71)
(214, 72)
(214, 73)
(214, 74)
(214, 75)
(214, 76)
(214, 77)
(214, 78)
(214, 79)
(214, 80)
(214, 81)
(214, 82)
(214, 83)
(214, 84)
(214, 85)
(214, 86)
(214, 87)
(214, 88)
(214, 89)
(214, 90)
(214, 91)
(214, 92)
(214, 93)
(214, 94)
(214, 95)
(214, 96)
(214, 97)
(214, 98)
(214, 99)
(214, 100)
(214, 101)
(214, 102)
(214, 103)
(214, 104)
(214, 105)
(214, 106)
(214, 107)
(214, 108)
(214, 109)
(214, 110)
(214, 111)
(214, 112)
(214, 113)
(214, 114)
(214, 115)
(214, 116)
(214, 117)
(214, 118)
(214, 119)
(214, 120)
(214, 121)
(214, 122)
(214, 123)
(214, 124)
(214, 125)
(214, 126)
(214, 127)
(214, 128)
(214, 129)
(214, 130)
(214, 131)
(214, 132)
(214, 133)
(213, 133)
(212, 133)
(211, 133)
(210, 133)
(209, 133)
(208, 133)
(207, 133)
(206, 133)
(205, 133)
(204, 133)
(203, 

#### LOGIC TO GET THE DIRECTION TO MOVE TO NEXT COORDINATE

In [8]:
x = 0
directions = []
while(x < len(points)):
    if(x == 0):
        x+=1
        continue
    else:
        if(points[x-1][0] < points[x][0]):
            direction = "east"
            x+=1
        elif(points[x-1][0] > points[x][0]):
            direction = "west"
            x+=1
        elif(points[x-1][1] < points[x][1]):
            direction = "south"
            x+=1
        elif(points[x-1][1] > points[x][1]):
            direction = "north"
            x+=1
        directions.append(direction)
            
    

#### TO STORE THE NUMBER OF TIMES ONE COMMAND HAS OCCURRED CONSECUTIVELY

In [14]:
x = 0
count = 0
command = directions[0]
commands = []
for direction in directions:
    if (command == direction):
        count+=1
        x+=1
    if (x+1 == len(directions)):
        if(command == direction):
            count+=1
            commands.append((command, count))
            continue
        else:
            commands.append((command, count))
            command = direction
            count = 1
            commands((command, count))
    
    if (command != direction):
        commands.append((command, count))
        command = direction
        count = 1
        x+=1

print(commands)


[('south', 84), ('west', 92)]
